FROM openjdk:21-jdk

# 设置工作目录
WORKDIR /app

# 复制已经编译好的jar文件到容器中
COPY target/*.jar app.jar

# 暴露应用端口（注意，这里是应用内部运行的端口，与Kubernetes的targetPort对应）
EXPOSE 8081

# 启动Spring Boot应用
CMD ["java", "-jar", "app.jar"]
