apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort # 或者 LoadBalancer, 依据需求
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30001 # 本地访问端口
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pjb3779/myfront-app:latest # 替换为你的前端镜像
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082" 
