apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: myapp
spec:
  type: NodePort # 或者 LoadBalancer, 依据需求
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 # 本地访问端口
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 2244509212/frontend:latest # 替换为你的前端镜像
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"  # 显式设置容器内部应用监听的端口
